[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
via_ir = true

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
fs_permissions = [
    { access = "read", path = "./assets/" },
    { access = "read", path = "./broadcast" },   
]

ffi = true
[etherscan]
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[profile.test]